name: .NET Core WPF Build and Release - RimSharp

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Needed for softprops/action-gh-release

jobs:
  build-and-release: # Combined job
    runs-on: windows-latest
    env:
      Project_Path: RimSharp.csproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed by softprops/action-gh-release to find the tag

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Extract Tag Name
      id: extract_tag
      run: echo "tag_name=${{ github.ref_name }}" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Check for Pre-release
      id: check_prerelease
      run: |
        if ("${{ github.ref_name }}" -match "-(alpha|beta|rc)") {
          echo "is_prerelease=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "is_prerelease=false" >> $env:GITHUB_OUTPUT
        }
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore $env:Project_Path

    - name: Build solution
      run: dotnet build $env:Project_Path --configuration Release --no-restore

    - name: Execute unit tests
      run: dotnet test $env:Project_Path --configuration Release --no-build

    - name: Publish and Package
      id: package
      run: |
        # Publish step
        dotnet publish $env:Project_Path `
          -r win-x64 `
          -c Release `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:PublishReadyToRun=true `
          -p:EnableCompressionInSingleFile=true `
          --output ./publish

        # Packaging step
        $folderName = "RimSharp"
        $zipName = "RimSharp_${{ steps.extract_tag.outputs.tag_name }}.zip"

        New-Item -ItemType Directory -Path $folderName
        Copy-Item -Path ./publish/* -Destination $folderName -Recurse

        Compress-Archive -Path $folderName -DestinationPath $zipName

        # Output the zip name for the release step
        echo "zip_name=$zipName" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        # tag_name: ${{ steps.extract_tag.outputs.tag_name }}
        name: RimSharp Release ${{ steps.extract_tag.outputs.tag_name }}
        body: |
          RimSharp WPF Application
          Tag: ${{ steps.extract_tag.outputs.tag_name }}
        prerelease: ${{ steps.check_prerelease.outputs.is_prerelease == 'true' }}
        files: ${{ steps.package.outputs.zip_name }}